### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by ghost** [ColinEberhardt/wasm-mandelbrot#8]
Is it normal that everything runs equally fast for me? It's all roughly ~650ms. Shouldn't WebAssembly be a whole lot faster than plain JavaScript?

**Comment by ColinEberhardt** [comment]
Yes, that is quite normal - see this blog post for further commentary https://blog.scottlogic.com/2017/10/17/wasm-mandelbrot.html

**Comment by ghost** [comment]
@ColinEberhardt thanks.
